on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
    - 'release/**'
  pull_request:
    branches:
    - main
    - master
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "VERSION=${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    - name: Install packages
      run: npm install
    - name: Copy over @authress/login SDK
      run: cp node_modules/@authress/login/dist/authress.min.js templates/assets/js/authress-login-sdk.min.js

    - name: Set up environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl
        coverage: xdebug

    - name: Install Composer dependencies
      run: |
        ./composer.phar config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
        ./composer.phar install --prefer-dist --optimize-autoloader

    - name: Run Lint
      run: ./vendor/bin/phpcs -i && ./vendor/bin/phpcs -s .

    - name: Clean workspace
      run: ./composer.phar install --prefer-dist --optimize-autoloader --no-dev

    - name: Set package versioning
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
      run: |
        sed -i "s/{{VERSION}}/${VERSION}/g" Authress_Sso_Login.php
        sed -i "s/{{VERSION}}/${VERSION}/g" wordpress/readme.txt
        cp wordpress/readme.txt readme.txt
    
    - name: WordPress.org plugin deployment
      id: wordpress_deploy
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
      uses: 10up/action-wordpress-plugin-deploy@2.3.0
      env:
        SVN_PASSWORD: ${{ secrets.WORDPRESS_SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.WORDPRESS_SVN_USERNAME }}
        SLUG: authress
        ASSETS_DIR: wordpress
        README_NAME: wordpress/readme.txt
      with:
        generate-zip: true

    - name: Create Release
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
      id: create_release
      uses: softprops/action-gh-release@v2.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        files: |
          authress.zip